import { PolicyDocument } from '@shared/schema';

interface ProcessedDocument extends PolicyDocument {
  extractedData: any;
}

interface CleanSummaryPreviewProps {
  document: ProcessedDocument | null;
  isLoading: boolean;
}

export function CleanSummaryPreview({ document, isLoading }: CleanSummaryPreviewProps) {
  if (isLoading) {
    return (
      <div className="bg-card rounded-lg shadow-sm border border-border p-8">
        <div className="animate-pulse">
          <div className="h-4 bg-muted rounded w-3/4 mb-4"></div>
          <div className="h-4 bg-muted rounded w-1/2 mb-6"></div>
          <div className="space-y-3">
            <div className="h-3 bg-muted rounded"></div>
            <div className="h-3 bg-muted rounded w-5/6"></div>
            <div className="h-3 bg-muted rounded w-4/6"></div>
          </div>
        </div>
      </div>
    );
  }

  if (!document || !document.summary) {
    return (
      <div className="bg-muted/50 rounded-lg border border-border p-8 text-center">
        <p className="text-muted-foreground">No summary available. Upload and process a document to see the analysis.</p>
      </div>
    );
  }

  return (
    <div className="bg-card rounded-lg shadow-sm border border-border">
      {/* Header */}
      <div className="border-b border-border px-8 py-6">
        <h2 className="text-2xl font-bold text-foreground mb-2">Policy Summary</h2>
        <p className="text-muted-foreground">Professional analysis of your insurance policy</p>
      </div>

      {/* Summary Content */}
      <div className="px-8 py-6">
        <div className="prose prose-slate dark:prose-invert max-w-none">
          <div className="text-foreground leading-relaxed space-y-4">
            {document.summary.split('\n').map((paragraph, index) => {
              // Skip empty lines
              if (paragraph.trim() === '') {
                return <div key={index} className="h-2"></div>;
              }

              // Handle bold headings (**text**)
              if (paragraph.includes('**')) {
                const parts = paragraph.split('**');
                return (
                  <div key={index} className="space-y-2">
                    {parts.map((part, partIndex) => {
                      if (partIndex % 2 === 1) {
                        // Bold text
                        return (
                          <h3 key={partIndex} className="text-lg font-semibold text-slate-900 mt-6 mb-3">
                            {part}
                          </h3>
                        );
                      } else if (part.trim()) {
                        // Regular text
                        return (
                          <p key={partIndex} className="text-slate-700 mb-3">
                            {part}
                          </p>
                        );
                      }
                      return null;
                    })}
                  </div>
                );
              }

              // Handle bullet points
              if (paragraph.trim().startsWith('•')) {
                return (
                  <div key={index} className="flex items-start space-x-3 py-1">
                    <span className="text-valley-primary mt-1 font-semibold">•</span>
                    <span className="text-slate-700 flex-1">
                      {paragraph.trim().substring(1).trim()}
                    </span>
                  </div>
                );
              }

              // Handle regular paragraphs
              return (
                <p key={index} className="text-slate-700 mb-4 leading-relaxed">
                  {paragraph}
                </p>
              );
            })}
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-slate-200 px-8 py-4 bg-slate-50">
        <p className="text-sm text-slate-500 text-center">
          Generated by Valley Trust Insurance Document Analysis System
        </p>
      </div>
    </div>
  );
}